name: namaz_vakti_app
description: "A new Flutter project."
publish_to: "none"
version: 1.5.0+33

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  blurrycontainer: ^2.1.0
  connectivity_plus: ^6.0.5
  csv: ^6.0.0
  device_calendar: ^4.3.3
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_compass: ^0.8.1
  flutter_localization: ^0.3.3
  flutter_native_splash: ^2.4.1
  flutter_svg: ^2.0.16
  geolocator: ^13.0.0
  google_fonts: ^6.2.1
  hijri: ^3.0.0
  html: ^0.15.4
  http: ^1.2.2
  in_app_review: ^2.0.10
  in_app_update: ^4.2.3
  permission_handler: ^11.3.1
  provider: ^6.1.2
  shared_preferences: ^2.3.1
  timezone: ^0.9.4
  translator: ^1.0.2
  url_launcher: ^6.3.0
  vibration: ^2.0.1
  xml: ^6.5.0
  just_audio: ^0.10.4
  cached_network_image: ^3.4.1
  android_intent_plus: ^5.3.0
  app_settings: ^6.1.1
  palette_generator: ^0.3.3+7
  share_plus: ^11.0.0
  page_flip_builder: ^0.1.4
  photo_view: ^0.15.0
  html_unescape: ^2.0.0
  dio: ^5.8.0+1
  audioplayers: ^6.5.0
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  webview_flutter: ^4.9.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/img/
    - assets/cities/
    - assets/svg/
    - assets/book_covers/
    - assets/icon/
    - assets/images/

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#1E1E1E"

  android_gravity: center
  ios_content_mode: center

  android: true
  ios: true
  web: false
  fullscreen: true

  image: assets/img/splash.png
  android_12:
    image: assets/img/splash.png
    icon_background_color: "#FFFFFF"
    image_dark: assets/img/splash.png
    icon_background_color_dark: "#1E1E1E"
