name: namaz_vakti_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.5.0+30

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  connectivity_plus: ^6.0.5
  csv: ^6.0.0
  device_calendar: ^4.3.3
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_compass: ^0.8.1
  flutter_localization: ^0.2.2
  flutter_native_splash: ^2.4.1
  flutter_svg: ^2.0.16
  geolocator: ^13.0.0
  google_fonts: ^6.2.1
  hijri: ^3.0.0
  html: ^0.15.4
  http: ^1.2.2
  in_app_review: ^2.0.10
  in_app_update: ^4.2.3
  intl: ^0.19.0
  permission_handler: ^11.3.1
  provider: ^6.1.2
  shared_preferences: ^2.3.1
  timezone: ^0.9.4
  translator: ^1.0.2
  url_launcher: ^6.3.0
  vibration: ^2.0.1
  xml: ^6.5.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/img/
    - assets/cities/
    - assets/svg/

# Flutter Native Splash Yapılandırması
flutter_native_splash:
  # Ana logo resmi
  image: assets/img/logo.png
  
  # Açık tema - temiz beyaz arkaplan
  color: "#FFFFFF"
  
  # Koyu tema - uygulamanızın koyu temasına uygun
  color_dark: "#1E1E1E"
  
  # Android 12+ için optimize edilmiş ayarlar
  android_12:
    # Logo görseli
    image: assets/img/logo.png
    # Android 12+ icon_background_color (açık tema)
    icon_background_color: "#FFFFFF"
    # Android 12+ icon_background_color (koyu tema) 
    icon_background_color_dark: "#1E1E1E"
  
  # iOS için özel optimizasyonlar
  ios: true
  
  # Web için ayarlar
  web: false
  
  # Tam ekran splash (kenarlarda boşluk olmasın)
  fullscreen: true
  
  # Logo görselinin boyutlandırma ayarları
  image_dark: assets/img/logo.png